 version: 2.1

 executors:
   java:
     docker:
       - image: circleci/openjdk:11-jdk-stretch

 jobs:
   build:
     executor: java
     steps:
       - checkout
       - run:
           name: Build
           command: |
             make build
   publish:
     executor: java
     steps:
       - checkout
       - run:
           name: Publish
           command: |
             make publish

 workflows:
   default:
     jobs:
       - build
       - publish:
           context: gradle-plugin
           requires:
             - build
           filters:
             branches:
               only: master